module.exports = {
  JOIN_GAME: 'JOIN_GAME',
  JOIN_GAME_SUCCESS: 'JOIN_GAME_SUCCESS',
  REJOIN_GAME: 'REJOIN_GAME',
  REJOIN_GAME_SUCCESS: 'REJOIN_GAME_SUCCESS',
  UPDATE_PLAYERS: 'UPDATE_PLAYERS',
  CLICK_CELL: 'CLICK_CELL',
  NEW_GAME_STATE: 'NEW_GAME_STATE',
  ADD_PATTERN: 'ADD_PATTERN'
};
