module.exports = {
  GAME_WIDTH: 100,
  GAME_HEIGHT: 50,
  REFRESH_INTERVAL: 50,
  TIME_TO_IDLE: 2000,
  CLEANUP_INTERVAL: 30000,
  UNDER_POPULATION_THRESHOLD: 2,
  OVERCROWDING_THRESHOLD: 3,
  REPRODUCTION_LIMIT: 3,
  GRID_SIZE: 10,
  CONNECTION_RETRY_MIN_INTERVAL: 500,
  CONNECTION_RETRIES: 5
};
